name: Trivial Reusable
on:
  workflow_call:
jobs:
  noop:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo "hello from reusable with write permission requested"
